spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
    # This optional means that, if the config server is not available then still the application will start. It won't fail.